name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Check formatting
        run: npm run format:check

      - name: Run type check
        run: npm run typecheck

      - name: Run build
        run: npm run build

      - name: Check for uncommitted changes in dist
        run: |
          if [ -n "$(git status --porcelain dist/)" ]; then
            echo "::error::Uncommitted changes found in dist directory after build"
            echo "Please run 'npm run build' locally and commit the changes"
            git diff dist/
            exit 1
          fi
