name: Create Release PR

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ labeled, unlabeled ]

permissions: {}

jobs:
  release-pr:
    permissions:
      contents: write
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Create or update release PR
        uses: ./.
