name: Test Action

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
  push:
    branches:
      - main
      - test/**

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run create-release-pr action
        uses: ./
        id: release-pr
        env:
          ACTIONS_STEP_DEBUG: true
          ACTIONS_RUNNER_DEBUG: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-branch: main
          release-branch: release/pr
          label-major: bump:major
          label-minor: bump:minor
          label-patch: bump:patch

      - name: Show outputs as JSON
        run: |
          cat <<EOF | jq .
          {
            "state": "${{ steps.release-pr.outputs.state }}",
            "pr_number": "${{ steps.release-pr.outputs.pr_number }}",
            "pr_url": "${{ steps.release-pr.outputs.pr_url }}",
            "pr_branch": "${{ steps.release-pr.outputs.pr_branch }}",
            "current_tag": "${{ steps.release-pr.outputs.current_tag }}",
            "next_tag": "${{ steps.release-pr.outputs.next_tag }}",
            "bump_level": "${{ steps.release-pr.outputs.bump_level }}",
            "release_notes": "${{ steps.release-pr.outputs.release_notes }}"
          }
          EOF
